---
title: "Page A"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## INEGI API

The package also has special functions to download data from the [INEGI API](http://www.inegi.org.mx/desarrolladores/indicadores/apiindicadores.aspx) using the [inegiR]() package

1) You must have a [token](http://www3.inegi.org.mx//sistemas/api/indicadores/v1/tokenVerify.aspx) to use this functionality. It's free and easy to get by visiting the [INEGI website](http://www3.inegi.org.mx//sistemas/api/indicadores/v1/tokenVerify.aspx)
2) The function plots the most recent value provided by the API
3) You'll have to lookup the indicator code at the [INEGI](http://www.inegi.org.mx/desarrolladores/indicadores/apiindicadores.aspx)

```{r, warning=FALSE}
library(mxmaps)

# Insert token here
# If you don't have one you can get it here: http://www3.inegi.org.mx//sistemas/api/indicadores/v1/tokenVerify.aspx
token <- ""

mxc_regions <- subset(df_mxmunicipio, metro_area == "Valle de México")$region
choropleth_inegi(token, mxc_regions, 
                 indicator = "1006000044", 
                 silent = FALSE)

state_regions <- df_mxstate$region
choropleth_inegi(token, state_regions, 
                 indicator = "3101008001")
hexbin_inegi(token, state_regions, 
             indicator = "3106002001")
```
